apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1883 # MQTT port
        - containerPort: 18083 # Dashboard port
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  type: NodePort
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 31580
  - port: 18083
    targetPort: 18083
    nodePort: 31055
  selector:
    app: emqx
