- hosts: local
  become: yes
  tasks:
    - name: Ensure /usr/local/bin directory exists
      file:
        path: /usr/local/bin
        state: directory
        mode: '0755'

    - name: Apply EMQX Persistent Volume and Persistent Volume Claim configuration
      command: microk8s kubectl apply -f /path/to/emqx-pvc.yaml
      become: yes

    - name: Apply EMQX Deployment and Service configuration
      command: microk8s kubectl apply -f /path/to/emqx-deployment.yaml
      become: yes

    - name: Wait for EMQX deployment to be ready
      shell: |
        microk8s kubectl rollout status deployment/emqx-deployment
      register: rollout_result
      retries: 5
      delay: 10
      until: rollout_result.stdout.find('successfully rolled out') != -1
      environment:
        PATH: "{{ ansible_env.PATH }}:/snap/bin"
      become: yes
