apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  postgres-user: ZHJvcHdpemFyZAo=  # base64-encoded username 'dropwizard'
  postgres-password: cGFzc3dvcmQK  # base64-encoded password 'password'
